version: '3.8'
services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.1
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.1
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - elastic
    depends_on:
      - elasticsearch  
  
  logstash:
    image: docker.elastic.co/logstash/logstash:7.16.1
    container_name: logstash
    ports:
      - "5044:5044"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    networks:
      - elastic
    depends_on:
      - elasticsearch  
      
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.16.1
    container_name: filebeat
    user: root
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /var/lib/docker/containers:/var/lib/docker/containers
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - elastic
    depends_on:
      - elasticsearch      

  mysqldb:
    image: mysqldb
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: Avaya@123
    ports:
      - "3306:3306"
    volumes:
      ./mysqldb/ssdb_roles.sql:/docker-entrypoint-initdb.d/1.sql"
      ./mysqldb/ssdb_user_role.sql:/docker-entrypoint-initdb.d/2.sql"
      ./mysqldb/ssdb_users.sql:/docker-entrypoint-initdb.d/3.sql"
      ./mysqldb/ssdb_category.sql:/docker-entrypoint-initdb.d/4.sql"
      ./mysqldb/ssdb_product.sql:/docker-entrypoint-initdb.d/5.sql"
      ./mysqldb/ssdb_orders.sql:/docker-entrypoint-initdb.d/6.sql"
    networks:
      - elastic
      
volumes:
  es-data:
    driver: local

networks:
  elastic:
    driver: bridge
